### PR TITLE
Add a banner.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Review by heerener — APPROVED** [review]
Fancy!

**Review by pramodk — APPROVED** [review]
Nice one! I see no permissions to merge this! 😃

**Comment by matz-e** [comment]
Well, I was the only one with any privileges :shrug: 

Added HPC as write, Erik as admin now.

**Comment by pramodk** [comment]
No worries! Just wanted to merge right away but didn't see Merge button :)

**Pull request merged**
